### ISSUE TITLE
TVMScript Printer TODO Items

### ISSUE THREAD

**Issue by junrushao** [junrushao/tvm#100]
## Arch

- [x] Managing dispatch token 
- [x] Fragment printing
- [x] Metadata
- [x] SEqual rendering with ObjectPath

## Sugars
- [x] Block: Sugar remap
- [x] Other: Sugar allocate + decl_buffer
- [x] PrimFunc + block: Sugar root block
- [x] PrimFunc: Sugar T.Buffer in `tir.PrimFunc.buffer_map`

## TIR

- [x] Handle tir.IterVar where `IterVar.var` is not defined.
- [x] Handle `T.Let` expression with scoping
- [x] Handle `T.SeqStmt` for fragment printing
- [x] Define buffer var
- [x] init block
