### ISSUE TITLE
Upstreaming Plan

### ISSUE THREAD

**Issue by junrushao** [junrushao/tvm#30]
Based on this commit: https://github.com/junrushao1994/tvm/commit/538805fd0cf485d508e5d6d6e36acc01519c9f2a

## Part 1. TIR passes

- A1. Update passes: verify GPU, compact buffer region, flatten buffer, lower cross thread reduction
```
src/tir/analysis/verify_gpu_code.cc
src/tir/transforms/compact_buffer_region.cc
tests/python/unittest/test_tir_transform_compact_buffer_region.py
src/tir/transforms/flatten_buffer.cc
tests/python/unittest/test_tir_transform_flatten_buffer.py
src/tir/transforms/lower_cross_thread_reduction.cc
```
- A2. New pass: apply block bound predicate, renormalize split pattern
```
### src/tir/transforms/apply_block_bound_predicate.cc
### tests/python/unittest/test_tir_transform_apply_block_bound_predicate.py
src/tir/transforms/renormalize_split_pattern.cc
tests/python/unittest/test_tir_transform_renormalize_split_pattern.py
```
- A3. Update: Misc
```
include/tvm/tir/transform.h
src/driver/driver_api.cc
python/tvm/tir/transform/transform.py
tests/python/unittest/test_tir_transform_inject_software_pipeline.py
```

## Part 2. MetaSchedule

- A4. Rules & Algorithm
```
src/meta_schedule/postproc/verify_gpu_code.cc
tests/python/unittest/test_meta_schedule_postproc_verify_gpu_code.py
src/meta_schedule/space_generator/post_order_apply.cc
src/meta_schedule/feature_extractor/per_store_feature.cc
src/meta_schedule/measure_callback/update_cost_model.cc
tests/python/unittest/test_meta_schedule_post_order_apply.py
tests/python/unittest/test_meta_schedule_mutator.py
tests/python/unittest/test_meta_schedule_schedule_rule.py
tests/python/unittest/test_meta_schedule_postproc.py
tests/python/unittest/test_meta_schedule_feature_extractor.py
```
- A5. Interface
```
include/tvm/meta_schedule/tune_context.h
python/tvm/meta_schedule/integration.py
python/tvm/meta_schedule/tune.py
tests/python/unittest/test_meta_schedule_tune_tir.py
```
- A6. Misc
```
include/tvm/meta_schedule/builder.h
python/tvm/meta_schedule/builder/builder.py
python/tvm/meta_schedule/builder/local_builder.py
python/tvm/meta_schedule/runner/rpc_runner.py
tests/python/unittest/test_meta_schedule_schedule_rule_cross_thread_reduction.py
tests/python/unittest/test_meta_schedule_schedule_rule_random_compute_location.py
tests/python/unittest/test_meta_schedule_postproc_rewrite_unbound_block.py
```
- A7. TensorCore
```
include/tvm/meta_schedule/schedule_rule.h
src/meta_schedule/schedule_rule/multi_level_tiling.cc
python/tvm/meta_schedule/schedule_rule/multi_level_tiling.py
tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py
python/tvm/meta_schedule/postproc/__init__.py
python/tvm/meta_schedule/postproc/rewrite_tensor_core.py
src/meta_schedule/postproc/rewrite_cooperative_fetch.cc
src/meta_schedule/postproc/rewrite_reduction_block.cc
src/meta_schedule/postproc/rewrite_tensor_core.cc
tests/python/unittest/test_meta_schedule_postproc_rewrite_cooperative_fetch.py
tests/python/unittest/test_meta_schedule_postproc_rewrite_tensor_core.py
```
- A8. End-to-end tests
```
tests/python/unittest/test_meta_schedule_sketch_cpu.py
tests/python/unittest/test_meta_schedule_sketch_cuda.py
tests/python/unittest/test_meta_schedule_task_extraction.py
```

## Part 3. Schedule primitives

- A9. Index map && Layout transformation
```
python/tvm/tir/function.py
include/tvm/tir/function.h
src/tir/ir/function.cc
python/tvm/tir/schedule/analysis.py
src/tir/schedule/analysis/layout.cc
src/tir/schedule/primitive/layout_transformation.cc
tests/python/unittest/test_tir_schedule_transform_layout.py
tests/python/unittest/test_tir_schedule_analysis.py
```
- A10. Tensorize
```
src/tir/schedule/analysis.h
src/tir/schedule/analysis/analysis.cc
src/tir/schedule/transform.cc
```
- A11. Misc
```
src/tir/schedule/instruction_traits.h
src/tir/schedule/utils.h
tests/python/unittest/test_tir_schedule_trace.py
```
- A12. Interface
```
include/tvm/tir/schedule/schedule.h
python/tvm/tir/schedule/schedule.py
python/tvm/tir/schedule/__init__.py
src/tir/schedule/concrete_schedule.cc
src/tir/schedule/concrete_schedule.h
src/tir/schedule/primitive.h
src/tir/schedule/schedule.cc
src/tir/schedule/traced_schedule.cc
src/tir/schedule/traced_schedule.h
```
- A13. Update primitives
```
src/tir/schedule/primitive/block_annotate.cc
src/tir/schedule/primitive/compute_inline.cc
src/tir/schedule/primitive/loop_transformation.cc
src/tir/schedule/primitive/reduction.cc
tests/python/unittest/test_tir_schedule_rfactor.py
tests/python/unittest/test_tir_schedule_split_fuse.py
```
- A14. New primitive: read-at && write-at
```
tests/python/unittest/test_tir_schedule_read_write_at.py
src/tir/schedule/primitive/read_write_at.cc
```

## Part 4. Arithmetic analysis

A15. 

```
### include/tvm/arith/int_set.h
### src/support/nd_int_set.h
### src/arith/int_set.cc
src/arith/iter_affine_map.cc
src/arith/modular_set.cc
src/arith/rewrite_simplify.cc
tests/python/unittest/test_arith_intset.py
tests/python/unittest/test_arith_iter_affine_map.py
tests/python/unittest/test_arith_modular_set.py
tests/python/unittest/test_arith_rewrite_simplify.py
```

## Part 5. Misc

A16

```
src/tir/ir/stmt_functor.cc
include/tvm/tir/stmt.h
include/tvm/tir/stmt_functor.h
include/tvm/tir/var.h
python/tvm/script/tir/scope_handler.py
python/tvm/driver/build_module.py
python/tvm/tir/__init__.py
```

**Comment by junrushao** [comment]
@jinhongyii:
- [ ] A3. Misc TIR updates
- [x] A6. Misc MetaSchedule updates
- [x] A11. Misc TIR schedule

@MasterJH5574 
- [x] <del>A12. TIR schedule interface</del>
- [x] A16. Misc updates

@spectrometerHBH 
- [x] A2. New TIR passes
- [x] A15. Arithmetic analysis

@Hzfengsy 
- [x] A1. Updating TIR passes
- [x] A13. Update TIR schedule primitives
- [ ] A4. MetaSchedule rules and algorithms

@zxybazh 
- [x] A5. MetaSchedule interfaces

@vinx13 
- [ ] A9. Index map && Layout transformation
- [x] ~~A10. Tensorize~~ (not needed or auto tensororization related)

No need to upstream:
- A7. TensorCore-specific
- A8. End-to-end tests

**Comment by masahi** [comment]
> No need to upstream:
> 
>     * A7. TensorCore-specific
> 
>     * A8. End-to-end tests

Why is that?

**Comment by junrushao** [comment]
A7 is under development and please sync with @vinx13.

A8 is basically some testing scripts...maybe TLCBench is a better place?
