### ISSUE TITLE
[TVMScript] TODO Items in Design

### ISSUE THREAD

**Issue by junrushao** [junrushao/tvm#43]
AST
- [x] Stable Doc AST: https://github.com/junrushao1994/tvm/pull/44
- [x] Python 3.6-3.10 compatibility: https://github.com/junrushao1994/tvm/pull/56
    - New & deprecation: https://greentreesnakes.readthedocs.io/en/latest/nodes.html
- [x] Nested parsing of decorators: Allow nest parsing #50 
- [ ] Mutual function call, which may require two-pass parsing

Evaluator
- [x] Call-site error reporting. https://github.com/junrushao1994/tvm/pull/52
- [ ] (low-priority) Arg-level error reporting

TVM
- [x] DiagnosticContext integration. https://github.com/junrushao1994/tvm/pull/53
- [x] Handle squared brackets. https://github.com/junrushao1994/tvm/pull/51
- [x] Handle type annotation like `T.int32` instead of casting. Support `T.handle`: https://github.com/junrushao1994/tvm/pull/51

**Comment by junrushao** [comment]
Engineering TODO items:

- [x] fix AST for python <= 3.8 
- [x] capture using `__global__`
- [x] make sure parsing results are correct using structural equality check
